### ISSUE TITLE
Repository containing malicious files

### ISSUE THREAD

**Issue by flipp33r** [PratDaBrat/JavaPacman#2]
Hi,
I hate to be a bearer of bad news, but it looks like this repository contains malware that you are likely not aware of.
Please treat this as a friendly notification. I suggest you to investigate origin of the below-mentioned file(s) and assume all systems involved in building or running your NetBeans project(s) to be fully compromised. I also suggest you to review all your other repositories and NetBeans projects for presence of similar files.

Suspicious file(s):

- https://github.com/PratDaBrat/JavaPacman/blob/master/nbproject/cache.dat - This is a malicious file intended to install additional malware on a system and/or modify NetBeans projects (see VirusTotal: https://www.virustotal.com/gui/file/a7d664bff764bfc2cc6b13c15b2d7d7f09d0e55f0c376a81b64644d85ebe1e0b/detection)
- https://github.com/PratDaBrat/JavaPacman/blob/master/nbproject/build-impl.xml#L957 - This is a modified `build-impl.xml` file intended to run malicious JAR file `cache.dat` every time a project is build

Cheers,
Flipper

**Comment by PratDaBrat** [comment]
Thanks Flipper for bringing this to my notice, I'll be sure to look into this and get to the bottom of it asap.
This was totally not intended and any inconvenience caused is regretted.
Cheers,
PC

**Comment by PratDaBrat** [comment]
cache.dat at nbproject has been removed.
Thanks again and the inconvenience is regretted.
PC :v:
